# Generated by Django 3.2.4 on 2021-06-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210625_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookimage',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='book-thumbnails'),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(upload_to='book-images'),
        ),
    ]
