# Generated by Django 4.1.1 on 2022-10-17 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_address_id_alter_basket_id_alter_basketline_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_spoken_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cs_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Processing'), (3, 'Sent'), (4, 'Cancelled')], default=1),
        ),
    ]
