# Generated by Django 3.2.4 on 2021-06-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210626_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktag',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.BookTag'),
        ),
    ]
