# Generated by Django 4.1.2 on 2022-10-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_city_address_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Submitted')], default=0),
        ),
    ]
